export default {
  info: [
    {
      text: 'Volusion',
      title: "Click to go to Volusion's website",
      href: 'http://volusion.com',
      external: true,
      icon: ['fas', 'briefcase'],
      type: 'work',
      enabled: true,
    },
    {
      text: 'NewPoint Media',
      title: "Click to go to NewPoint Media's website",
      href: 'http://newpointmediagroup.com/',
      external: true,
      icon: ['fas', 'briefcase'],
      type: 'work',
      enabled: true,
    },
    {
      text: 'BloomTech',
      title: 'Click to learn more about BloomTech',
      href: 'https://www.bloomtech.com/',
      external: true,
      icon: ['fas', 'graduation-cap'],
      type: 'education',
      enabled: true,
    },
    {
      text: 'University of Washington',
      title: 'Click to learn more about the University of Washington',
      href: 'https://sefs.uw.edu/students/undergraduate/bse-major/',
      external: true,
      icon: ['fas', 'graduation-cap'],
      type: 'education',
      enabled: true,
    },
  ],
};
