export default {
  location: 'Austin, TX',
  skills: {
    primarySkills: [
      {
        text: 'Agile',
        title: 'Click to learn more about Agile workflow',
        link: 'https://www.atlassian.com/agile/project-management/workflow',
        icon: ['fab', 'jira'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'AWS',
        title: 'Click to learn more about AWS',
        link: 'https://aws.amazon.com/',
        icon: ['fab', 'aws'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'cli',
        title: 'Click to learn more about macOS Terminal',
        link: 'https://support.apple.com/guide/terminal/welcome/mac',
        icon: 'icon-shell',
        type: 'fz',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Docker',
        title: 'Click to learn more about Docker',
        link: 'https://www.docker.com',
        icon: ['fab', 'docker'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Express',
        title:
          'Click to learn more about ExpressJS, a Node.js backend framework',
        link: 'https://expressjs.com/',
        icon: ['fas', 'server'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'GCP',
        title: 'Click to learn more about Google Cloud Platform',
        link: 'https://cloud.google.com',
        icon: ['fab', 'google'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Git',
        title: 'Click to learn more about Git',
        link: 'https://git-scm.com',
        icon: 'icon-git',
        type: 'fz',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'JavaScript',
        title: 'Click to learn more about JavaScript from MDN',
        link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        icon: ['fab', 'js-square'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'macOS',
        title: 'Click to learn more about macOS',
        link: 'https://www.apple.com/macos',
        icon: ['fab', 'apple'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Microservices',
        title: 'Click to learn more about microservices',
        link: 'https://aws.amazon.com/microservices/',
        icon: ['fas', 'layer-group'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Node.js',
        title: 'Click to learn more about Node.js',
        link: 'https://nodejs.org/en/',
        icon: ['fab', 'node-js'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'npm',
        title: 'Click to learn more about npm',
        link: 'https://www.npmjs.com',
        icon: ['fab', 'npm'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'PostgreSQL',
        title: 'Click to learn more about PostgreSQL',
        link: 'https://www.postgresql.org/',
        icon: 'icon-postgres',
        type: 'fz',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'React',
        title: 'Click to learn more about React',
        link: 'https://reactjs.org',
        icon: ['fab', 'react'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'Redis',
        title: 'Click to learn more about Redis',
        link: 'https://redis.com',
        icon: 'icon-redis',
        type: 'fz',
        set: 'primary',
        enabled: true,
      },
      {
        text: 'TypeScript',
        title: 'Click to learn more about TypeScript',
        link: 'https://www.typescriptlang.org',
        icon: ['fas', 'code'],
        type: 'fa',
        set: 'primary',
        enabled: true,
      },
    ],
    secondarySkills: [
      {
        text: 'MySQL',
        title: 'Click to learn more about MySQL',
        link: 'https://www.mysql.com',
        icon: 'icon-mysql-alt',
        type: 'fz',
        set: 'secondary',
        enabled: true,
      },
      {
        text: 'PHP',
        title: 'Click to learn more about PHP',
        link: 'https://www.php.net/',
        icon: ['fab', 'php'],
        type: 'fa',
        set: 'secondary',
        enabled: true,
      },
    ],
  },
};
